config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :barks

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  root 'barks#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bark.rb
class Bark < ApplicationRecord

  validates :title, presence: true
  validates :location, presence: true
  validates :content, presence: true

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  include BCrypt

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password_hash, presence: true

  has_many :barks

  # Return a BCrypt password or make a new one out of password_hash
  def password
    @password ||= Password.new(password_hash)
  end

  # Create a BCrypt password and set password_hash to equal the new BCrypt password
  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  # Create a new user
  def create
    @user = User.new(params[:user])
    @user.password = params[:password_hash]
    @user.save!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/barks_controller.rb
class BarksController < ApplicationController

  def index
    @barks = Bark.all
    if current_user
      @user = current_user
    end
  end

  def create
    @user = current_user
    @bark = @user.barks.new(bark_params)

    if @bark.save
      redirect_to root_path
    else
      redirect_to new_bark_path
    end
  end

  def new
    @bark = Bark.new
  end

  def edit
    find_bark
  end

  def show
    find_bark
  end

  def update
    find_bark
    if @bark.update_attributes(bark_params)
      redirect_to bark_path(params[:id])
    else
      redirect_to edit_bark_path(params[:id])
    end
  end

  def destroy
    find_bark
    @bark.destroy
    redirect_to root_path
  end

  private
    def bark_params
      params.require(:bark).permit(:title, :location, :content)
    end

    def find_bark
      @bark = Bark.find(params[:id])
    end

    def current_user
      if session[:user_id]
        @user = User.find(session[:user_id])
      else
        nil
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.password == params[:password]
      login(@user)
      redirect_to root_path
    else
      redirect_to '/login'
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

  private
    # Create a new session with user
    def login(user)
      session[:user_id] = user.id
    end

    # Clear session
    def logout
      session.clear
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    @user.password = params[:user][:password_hash]
    if @user.save
      login(@user)
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  def new
    @user = User.new
  end

  def edit
    find_user
  end

  def show
    find_user
  end

  def update
    find_user
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    find_user
    @user.destroy
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :email)
    end

    def find_user
      @user = User.find(params[:id])
    end

    # Create a new session with user
    def login(user)
      session[:user_id] = user.id
    end

    # Return current user logged into session
    def current_user
      if session[:user_id]
        User.find(session[:user_id])
      else
        nil
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barks_helper.rb
module BarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Create a new session with user
  def login(user)
    session[:user_id] = user.id
  end

  # Clear session
  def logout
    session.clear
  end

  # Return current user logged into session
  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      nil
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Create a new session with user
  def login(user)
    session[:user_id] = user.id
  end

  # Clear session
  def logout
    session.clear
  end

  # Return current user logged into session
  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      nil
    end
  end
end

app/views/barks/_form.html.erb
<%= form_for @bark do |f| %>

  <% if @bark.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@bark.errors.count, "error") %> prohibited
        this Bark from being saved:
      </h2>
      <ul>
        <% @bark.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
  </p>

  <p>
    <%= f.label :location %>
    <%= f.text_field :location %><br>
  </p>

  <p>
    <%= f.label :content %>
    <%= f.text_area :content %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/barks/edit.html.erb
<h1>Update this Bark!</h1>

<%= render 'form' %>
<%= link_to 'All Barks', root_path %>

app/views/barks/index.html.erb
<h1>Barks#Index Page</h1>

<div id='links'>
  <% if !current_user %>
  <section id='not-logged-in'>
    <%= link_to 'Register New User', new_user_path %><br>
    <%= link_to 'Sign-In Returning User', '/login' %><br>
  </section>
  <% else %>
  <section id='logged-in'>
    <h2>Welcome <%=current_user.username%>!</h2>
    <%= link_to 'Your Profile', user_path(@user) %>
    <%= link_to 'Create a New Bark!', new_bark_path %><br>
    <%= link_to 'Sign Out', logout_path %>
  </section>
  <% end %>
</div>

<div id='all-barks'>
  <% if @barks %>
    <% @barks.each do |bark| %>
      <li class='li bark'>
        <%= link_to "#{bark.title}", bark_path(bark) %> <br>
      </li>
    <% end %>
  <% end %>
</div>

app/views/barks/new.html.erb
<h1>Create a New Bark</h1>

<%= render 'form' %>
<%= link_to 'All Barks', root_path %>

app/views/barks/show.html.erb
<h1 class='bark-title'><%=@bark.title%></h1>

<p>Location: <%=@bark.location%></p>
<p class='bark-content'><%=@bark.content%></p>

<% if current_user && @bark.user_id == current_user.id %>
  <%= link_to 'Edit this Bark!', edit_bark_path(@bark) %><br>
  <%= form_tag(bark_path(@bark), method: 'delete') do %>
    <input type='submit' value='Delete this Bark?'>
  <% end %>
<% end %>
<%= link_to 'All Barks', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarkAlong</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this User from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :username %>
    <%= f.text_field :username %><br>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %><br>
  </p>

  <p>
    <%= f.label :first_name %>
    <%= f.text_area :first_name %><br>
  </p>

  <p>
    <%= f.label :last_name %>
    <%= f.text_area :last_name %><br>
  </p>

  <p>
    <%= f.label :password_hash %>
    <%= f.password_field :password_hash %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/edit.html.erb
<h1>Edit User Details Form</h1>

<%= render 'form' %>
<%= link_to 'Home', root_path %>

app/views/users/index.html.erb
<h1>Users#Index Page</h1>

<% if @users %>
  <h2>List of Bark Along! Followers: </h2>
  <ul id='all-users-list'>
    <% @users.each do |user| %>
      <li class='list-user-username'> <%=user.username%> </li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Register New User Form</h1>

<%= render 'form' %>
<%= link_to 'Home', root_path %>

app/views/users/show.html.erb
<h1>Welcome <%=@user.first_name%>!</h1>

<ul id='users-barks-list'>
  <% @user.barks.each do |bark| %>
    <li><%= link_to bark.title, bark_path(bark) %></li>
  <% end %>
</ul>

<%= link_to 'Home', barks_path %><br>
<%= link_to 'Sign Out', logout_path %><br>
<%= link_to 'Create New Bark!', new_bark_path %>